(()=>{
const VERSION='1.1.0', UPDATED='August 30, 2026', REPO='williamlodge/termux-field-guide';
const qs=(s,r=document)=>r.querySelector(s), esc=s=>String(s||'').trim();
const head=document.head;
let mv=qs('meta[name="version"]'); if(mv) mv.content=VERSION; else {mv=document.createElement('meta');mv.name='version';mv.content=VERSION;head.append(mv)}
let mu=document.createElement('meta');mu.name='last-updated';mu.content='2026-08-30';head.append(mu);
const meta=qs('.hero .meta'); if(meta && !qs('[data-pwa-version]',meta)){meta.insertAdjacentHTML('beforeend',`<span class="badge" data-pwa-version>Version ${VERSION}</span><span class="badge">Updated 2026-08-30</span><span class="badge">PWA / Offline</span>`)}
const hero=qs('.hero'); if(hero && !qs('.release-card')) hero.insertAdjacentHTML('afterend',`<dl class="release-card"><dt>Version</dt><dd>${VERSION}</dd><dt>Last updated</dt><dd>${UPDATED}</dd><dt>Offline</dt><dd>Yes — after the first successful PWA load.</dd><dt>Contributions</dt><dd>Community corrections can be opened directly as GitHub Issues.</dd></dl>`);
const top=qs('.topbar-inner'); if(top){const status=document.createElement('span');status.className='pwa-status';status.id='pwaStatus';status.innerHTML='<span class="pwa-dot"></span><span>ONLINE</span>';top.append(status);const install=document.createElement('button');install.className='pwa-action';install.id='pwaInstall';install.hidden=true;install.textContent='INSTALL';top.append(install)}
const status=qs('#pwaStatus'); function net(){if(status){qs('span:last-child',status).textContent=navigator.onLine?'ONLINE':'OFFLINE';status.title=navigator.onLine?'Network available':'Offline cache active'}} window.addEventListener('online',net);window.addEventListener('offline',net);net();
let deferred=null; const install=qs('#pwaInstall'); window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;if(install)install.hidden=false}); install?.addEventListener('click',async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;install.hidden=true}); window.addEventListener('appinstalled',()=>{if(install)install.hidden=true;deferred=null});
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./sw.js').catch(console.warn);
const sources=qs('#sources'); if(sources && !qs('#submissions')){
 const sec=document.createElement('section');sec.id='submissions';sec.dataset.search='';sec.innerHTML=`<h2>32 — Community updates & user submissions</h2><p>If a command changed, an Android release broke a workflow, an app became unsafe or abandoned, or something important is missing, submit a correction. The form builds the report locally and can open a prefilled GitHub Issue for review.</p><div class="callout"><strong>Privacy:</strong> Review the generated issue before sending. Never include private keys, API tokens, passwords, personal phone numbers, or private server addresses.</div><form id="communityForm"><div class="submission-grid"><div class="submission-field"><label>Submission type</label><select id="subType"><option>Correction</option><option>New tool/app</option><option>Command update</option><option>Android/version compatibility</option><option>Security warning</option><option>New guide section</option><option>Other</option></select></div><div class="submission-field"><label>Guide section</label><input id="subSection" placeholder="Example: 16 — Shizuku"></div><div class="submission-field full"><label>Short title</label><input id="subTitle" maxlength="140" required></div><div class="submission-field"><label>Device / Android</label><input id="subDevice" placeholder="Optional"></div><div class="submission-field"><label>Source URL</label><input id="subSource" type="url" placeholder="Official docs/release/issue"></div><div class="submission-field full"><label>Details</label><textarea id="subDetails" required placeholder="Describe what changed or should be added. Include exact commands/errors when useful."></textarea></div><div class="submission-field full"><label>Name / handle</label><input id="subName" maxlength="80" placeholder="Optional"></div></div><div class="submission-actions"><button class="pwa-action" type="submit">PREPARE</button><button class="pwa-action secondary" type="button" id="openIssue">OPEN GITHUB ISSUE</button><button class="pwa-action secondary" type="button" id="copySub">COPY</button><button class="pwa-action secondary" type="button" id="downloadSub">DOWNLOAD .TXT</button></div></form><div class="submission-output" id="subOutput"></div><h3>Review rules</h3><ul><li>Prefer official project docs, release notes, Android documentation, or reproducible tests.</li><li>Include exact device/build information for firmware-specific procedures.</li><li>Root/bootloader submissions should state device, firmware, partition target, and recovery path.</li><li>Community submissions are reviewed evidence, not automatically trusted instructions.</li></ul>`;sources.before(sec);
 const nav=qs('aside nav'); const srcLink=nav?.querySelector('a[href="#sources"]'); if(srcLink){const a=document.createElement('a');a.href='#submissions';a.textContent='32 — Community updates';nav.insertBefore(a,srcLink);srcLink.textContent='33 — Sources & verification'}
 const h=qs('#sources h2');if(h)h.textContent='33 — Sources & verification';
}
const form=qs('#communityForm'), out=qs('#subOutput');
function report(){const v=id=>esc(qs('#'+id)?.value);return ['TERMUX FIELD GUIDE COMMUNITY SUBMISSION',`Guide version: ${VERSION}`,`Prepared: ${new Date().toISOString()}`,'',`Type: ${v('subType')}`,`Section: ${v('subSection')||'Not specified'}`,`Title: ${v('subTitle')}`,`Device / Android: ${v('subDevice')||'Not specified'}`,`Source: ${v('subSource')||'Not provided'}`,`Name / handle: ${v('subName')||'Anonymous'}`,'','DETAILS',v('subDetails')].join('\n')}
function show(){if(out){out.textContent=report();out.style.display='block'}return report()}
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;show();save()});
function save(){if(!form)return;const ids=['subType','subSection','subTitle','subDevice','subSource','subDetails','subName'];localStorage.setItem('tfg-submission-draft',JSON.stringify(Object.fromEntries(ids.map(id=>[id,qs('#'+id)?.value||'']))))}
form?.addEventListener('input',save);
try{const d=JSON.parse(localStorage.getItem('tfg-submission-draft')||'null');if(d)Object.entries(d).forEach(([id,val])=>{const el=qs('#'+id);if(el)el.value=val})}catch{}
qs('#copySub')?.addEventListener('click',async()=>{const t=show();try{await navigator.clipboard.writeText(t)}catch{}});
qs('#downloadSub')?.addEventListener('click',()=>{const b=new Blob([show()],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='termux-field-guide-submission-'+new Date().toISOString().slice(0,10)+'.txt';a.click();URL.revokeObjectURL(u)});
qs('#openIssue')?.addEventListener('click',()=>{if(form && !form.reportValidity())return;const title='Guide submission: '+esc(qs('#subTitle')?.value),body=show();window.open(`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`,'_blank','noopener')});
const footer=qs('.footer strong');if(footer)footer.textContent=`TERMUX FIELD GUIDE / VERSION ${VERSION}`;
})();
